import React, { useEffect, useState } from 'react';
import axios from 'axios';
import './commander.css';
export default function CommanderDashboard(){
  const [data,setData]=useState(null),[error,setError]=useState('');
  useEffect(()=>{let alive=true;const load=async()=>{try{const {data:result}=await axios.get('/api/enterprise/brief');if(alive){setData(result);setError('');}}catch(e){if(alive){setData(null);setError(e.response?.status===404?'Commander access unavailable.':'Could not load current business analysis.');}}};load();const timer=setInterval(load,60000);return()=>{alive=false;clearInterval(timer);};},[]);
  const brief=data?.brief;
  return <main className="commander"><header><p className="commander-eyebrow">T.O.I. • PRIVATE COMMANDER CENTER</p><h1>Freedom Audit launch</h1><p>Enterprise intelligence · Observation and recommendations</p><span className="commander-badge">Consequential execution disabled</span></header>
    {error&&<p role="alert">{error}</p>}{!error&&!brief&&<p>Waiting for the first monitoring cycle…</p>}
    {brief&&<><p className="commander-update">Updated {new Date(data.lastSuccessAt).toLocaleString()} {data.stale?'· STALE — current state unverified':''} {data.lastError?'· Monitoring read failed':''}</p>
    <section className="commander-stats" aria-label="Launch results"><article><p>Customer sales</p><strong>{brief.revenue.sales??'Unavailable'}</strong><small>Founder checks excluded</small></article><article><p>Gross paid revenue</p><strong>{brief.revenue.amount===null?'Unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(brief.revenue.amount/100)}</strong><small>Before refunds and fees</small></article><article><p>Buyer traffic</p><strong>{brief.funnel.find(x=>x.stage==='Landing visits')?.count??'Not measured'}</strong><small>Browser events ≠ people</small></article></section>
    <section><h2>Commander brief</h2><p>{brief.diagnosis}</p><p>Window: {new Date(brief.window.start).toLocaleString()} → {new Date(brief.window.end).toLocaleString()}</p></section>
    <section><h2>Funnel and measurement coverage</h2><div className="commander-table"><table><thead><tr><th>Stage</th><th>Count</th><th>Coverage / source</th></tr></thead><tbody>{brief.funnel.map(row=><tr key={row.stage}><th>{row.stage}</th><td>{row.count??'—'}{row.founderValidationCount!==undefined&&<small>{row.founderValidationCount} founder checks excluded</small>}</td><td>{row.coverage}<small>{row.source}</small></td></tr>)}</tbody></table></div><p>No conversion percentage is shown without comparable, joined cohorts.</p></section>
    <section><h2>Team findings</h2><div className="commander-grid">{brief.findings.map(f=><article key={f.id}><span className="commander-badge">{f.severity}</span><h3>{f.title}</h3><ul>{f.evidence.map(e=><li key={e}>{e}</li>)}</ul><p>{f.recommendation}</p></article>)}</div></section>
    <section><h2>Approval queue</h2>{brief.approvalQueue.length?brief.approvalQueue.map(f=><article key={f.id}><h3>{f.title}</h3><p>{f.recommendation}</p><small>This dashboard cannot publish, spend or send messages.</small></article>):<p>No action requires your approval at this time.</p>}</section>
    <section><h2>Campaigns and channel state</h2>{brief.social.posts.map(p=><article key={p.id}><h3>{p.title||p.name}</h3><p>{p.platform} · {p.status} {p.errorCode?'· '+p.errorCode:''}</p><small>Platform attribution: {p.platformAttribution?'link tagged':'missing'} · Post attribution: {p.postAttribution?'link tagged':'missing'}</small></article>)}</section>
    <section><h2>Social measurement access</h2>{(brief.social.measurements||[]).map(m=><article key={m.postId}><h3>{m.provider}</h3><p>{m.status} · {m.classification||m.reason||m.period}</p>{Object.entries(m.metrics).map(([k,v])=><p key={k}>{k}: {v}</p>)}<small>Observed {new Date(m.observedAt).toLocaleString()}. No token refresh or account changes performed.</small></article>)}</section><section><h2>System health</h2><div className="commander-grid">{Object.entries(brief.health).map(([name,h])=><article key={name}><h3>{name}</h3><p>HTTP {h.status} {h.latencyMs!==undefined?`· ${h.latencyMs} ms`:''}</p><small>Availability check; not payment fulfillment proof</small></article>)}</div><p>Personal execution: {brief.personalExecution} · M3: {brief.m3}</p></section>
    <section><h2>Enterprise team</h2><ul>{brief.roles.map(r=><li key={r.name}>{r.name} — {r.status}</li>)}</ul><p>One shared coordinator. No continuous model calls.</p></section>
    <section><h2>Decision ledger</h2>{data.ledger.slice(0,10).map(l=><article key={l._id}><h3>{l.problem}</h3><p>{l.proposedIntervention}</p><small>Assessment: {l.decision} · Actual result: {l.actualResult||'Awaiting observation'}</small></article>)}</section></>}
  </main>;
}
