services:
  - type: web
    name: syzmeku-engine
    env: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm run render-build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: ENGINE_SIGNATURE
        value: "EL_KAI_THARION_KAI_ZHUN"
      - key: SYSTEM_VECTOR
        value: "TRIANGULUM_THETA_7"
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
