const longform=require('./longform');
const {VERSION,applyLearning}=require('./voice');
const TOPICS=[
 ['Information and application','You Know What to Do. What Keeps Getting in the Way?'],['Prioritization','What keeps getting to make the decision?'],['Freedom and time','Who owns the hour?'],['Life systems','You saved the advice. Now what?'],['Self-auditing','Do not make five new projects'],['Personal experiments','Try the change. Check what happened.'],['Patterns and intuition','A possibility is not a fact'],
 ['Competing obligations','Everybody Says Manage Your Time. Who Owns Yours?'],['Commitments','Which yes keeps costing you?'],['Resources','What would make the next step possible?'],['Decision making','Is that urgent, or just loud?'],['Prioritization','Name the thing that keeps winning'],['Application','Make the next action small enough to see'],['Outcomes','What changed when you tried it?'],
 ['Pattern recognition','You Keep Calling It a Pattern. What Repeated?'],['Evidence','One bad day is not your whole story'],['Intuition','Notice it. Then check it.'],['Hypotheses','What else could explain that?'],['Big SYZ concepts','Memory is useful when you can correct it'],['Life systems','Your plan needs somewhere to happen'],['Reflection','What worked when the conditions were different?'],
 ['Self-mastery','Before You Blame Yourself, Look at What Keeps Winning'],['Freedom and time','You cannot schedule the same hour twice'],['Assets','What do you already have that you can actually use?'],['Obligations','You can care without promising everything'],['Self-auditing','What should you fix first?'],['Application','Agreeing with advice is not the exercise'],['Outcomes','Keep it, change it, or stop doing it'],['Reflection','What did this month actually show you?'],['Next-month strategy','Keep the question that produced a useful answer'],
];
const DESTINATIONS={facebook:{cta:'Start your audit. Use the link in this post.',placement:'video',verified:false},instagram:{cta:'Open our profile. Choose Freedom Audit.',placement:'reel',verified:false},youtube:{cta:'Open our channel. Choose Freedom Audit.',placement:'short',verified:false},tiktok:{cta:'Open our profile. Choose Freedom Audit.',placement:'video',verified:false,pending:'Production review/OAuth approval pending'}};
const time=s=>`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s/60)%60).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')},${String(Math.round((s%1)*1000)).padStart(3,'0')}`;
const subtitles=scenes=>scenes.filter(s=>s.narration).map((s,i)=>`${i+1}\n${time(s.start)} --> ${time(s.end)}\n${s.narration}`).join('\n\n')+'\n';
function base(platform,title,type,day){return {platform,title,type,day,voiceVersion:VERSION,intensity:'direct',audience:'People juggling competing demands who want to identify a workable next step.',purpose:type==='sales'?'Explain the paid audit and its deliverables.':'Teach a usable idea before any relevant offer.',cta:DESTINATIONS[platform].cta,destination:{url:platform==='facebook'?'https://freedom.toisouljahacademy.com/':null,verified:false,verification:'Founder must verify the exact public destination; profile changes require approval.'},attribution:`fa_c0_${platform}_${type}_v1_d${String(day).padStart(2,'0')}`,hashtags:['LifeAudit','FreedomAudit'],keywords:['competing priorities','applying knowledge','life audit'],description:'',scenes:[],script:'',duration:24,aspectRatio:'9:16',cover:{text:title,style:'Existing Commander colors; large readable type; no invented portrait.'},cost:{amount:0,currency:'USD',paidGeneration:false},production:{status:'PACKAGE_READY_MEDIA_PENDING',media:null,method:'Prepared scenes, narration, subtitle timings and Google Vids inputs; no paid generation.'},schedule:{proposedDay:day,timeZone:'America/Chicago',publicSchedulingApproved:false},experiment:'Earlier explanation and visible deliverables; no causal claim without comparable measured outcomes.',evidence:['founder-c0-2026-09-10','E0 baseline','Variant B discovery specification'],recommendation:'A concrete question with a usable next step; offer remains optional.',audio:{voice:'Founder-approved recording or separately approved narrator; no voice cloning.',music:'None by default. Add only owned/licensed music after approval; keep speech intelligible.',processing:'Check full rendered media for continuity, dead air, clipping and unwanted speech.'},approvalExceptions:[]};}
function variant(platform){const p=base(platform,'Overwhelmed? What is actually running your day?','sales',1),cta=DESTINATIONS[platform].cta;
 p.scenes=[
 {start:0,end:2,narration:'Overwhelmed? What do you fix first?',screen:'What do you fix first?'},
 {start:2,end:5,narration:'Start with The Freedom Audit.',screen:'The Freedom Audit\nFive-domain life audit'},
 {start:5,end:8,narration:'Look at five areas of your life.',screen:'Time · Money · Obligations\nAssets · Desires'},
 {start:8,end:11,narration:'See your score. Find a starting point.',screen:'ILLUSTRATIVE DEMO\nFreedom Score: 60 / 100\nStarting point: protect usable time',demo:{score:60,domains:{Time:40,Money:60,Obligations:50,Assets:80,Desires:70},priority:'Confirm two protected work blocks.'}},
 {start:11,end:14,narration:'Get a plan for the next thirty days.',screen:'ILLUSTRATIVE DEMO\n30-Day Liberation Plan\nWeek 1: confirm two work blocks\nReview what happened before adding more'},
 {start:14,end:16,narration:'Thirty-seven dollars. One time.',screen:'$37 — one time'},
 {start:16,end:18,narration:'Start your audit.',screen:cta},
 {start:18,end:21,narration:'',screen:'Freedom Score + 30-Day Liberation Plan\n$37 — one time\n'+cta},
 {start:21,end:24,narration:platform==='facebook'?'Use the link in this post.':'Open our profile. Choose Freedom Audit.',screen:cta},
 ].map(s=>({...s,transition:'Direct cut; no flashing or generated footage.',asset:'Original editable text/product-demo scene; illustrative data only.'}));
 p.description='If everything is pulling at you, adding another list may not tell you what to fix first. The Freedom Audit looks at Time, Money, Obligations, Assets and Desires. You get a Freedom Score and a 30-Day Liberation Plan. $37 one time. '+cta;
 if(platform==='youtube')p.title='Overwhelmed? What Should You Fix First? | The Freedom Audit';
 if(platform==='tiktok')p.production.status='HOLD_TIKTOK_REVIEW_PENDING';
 return finish(p);
}
function finish(p){p.script=p.scenes.map(s=>s.narration).filter(Boolean).join('\n\n');p.subtitles=subtitles(p.scenes);return p;}
function longPackage(){const p=base('youtube',longform.title,'longform',1);let cursor=0;p.duration=0;p.aspectRatio='16:9';p.scenes=longform.sections.map((s,i)=>{const start=cursor;cursor+=Math.round(s.text.split(/\s+/).length/135*60)+5;return {start,end:cursor,narration:s.text,screen:s.title,chapter:s.title,asset:i===1?'Illustrative calendar; never real personal calendar.':'Founder-approved narration with editable text/examples; no unlicensed footage.',transition:'Cut at the paragraph break; preserve the argument.'};});p.duration=cursor;p.cta='Optional Freedom Audit — $37 one time. Link in the description.';p.destination.url='https://freedom.toisouljahacademy.com/';p.first30SecondHook={start:0,end:30,text:longform.sections[0].text.split('\n\n')[0],estimated:true};p.titleCandidates=longform.titleCandidates;p.thumbnailConcepts=longform.thumbnailConcepts;p.description=longform.description;p.keywords=longform.keywords;p.pinnedComment=longform.pinnedComment;p.extractions=longform.extractions.map(x=>({...x,start:p.scenes[x.section].start,end:p.scenes[x.section].end,sourceVersion:'longform-v1',note:'Select the self-contained argument and add its own opening; do not imply a customer outcome.'}));p.chapters=p.scenes.map(s=>({start:s.start,title:s.chapter}));p.production.estimatedDuration=true;return finish(p);}
function short(day,platform='youtube'){const [pillar,title]=TOPICS[day-1],p=base(platform,title,'education',day);p.pillar=pillar;p.duration=42;p.cta='Try it with one decision. Check what happened.';p.destination={url:null,verified:true,verification:'No external destination; standalone exercise.'};const sourceSection=({2:0,3:2,4:3,5:4,6:5,7:6,8:2,9:2,10:2,11:1,12:1,13:3,14:5,15:6,16:6,17:6,18:6,19:6,20:2,21:6,22:1,23:2,24:4,25:2,26:4,27:3,28:5,29:5,30:6})[day]||0;const excerpts=longform.sections[sourceSection];const paragraph=excerpts.text.split('\n\n')[1];p.scenes=[{start:0,end:4,narration:title,screen:title},{start:4,end:34,narration:paragraph,screen:'Use one specific situation.\nKeep personal details private.'},{start:34,end:42,narration:p.cta,screen:p.cta}].map(s=>({...s,transition:'Clean cut; one idea per segment.',asset:'Editable type and explicitly illustrative diagram; no customer data.'}));p.description=paragraph+' '+p.cta;p.extractions=[{source:'first-longform',section:sourceSection,relationship:'Adapted teaching excerpt; title and premise require QA.'}];return finish(p);}
function calendar(){return TOPICS.map(([pillar,title],i)=>({day:i+1,pillar,title,format:i===0?'Long-form + Variant B preparation':[7,14,21].includes(i)?'Long-form outline / production brief':'Short-form teaching excerpt',status:'PROPOSED — no public schedule',goal:i===0?'Introduce the exercise and prepare the paid-offer variant':'Standalone value; offer only when useful',source:i<7?'First long-form cluster':'Evergreen founder-authorized pillar; no fabricated trending claim'}));}
function catalog(){const items=['facebook','instagram','youtube','tiktok'].map(platform=>({id:'variant-b-'+platform,package:variant(platform)}));items.push({id:'first-longform',package:longPackage()});for(let day=2;day<=30;day++){const p=short(day);if([8,15,22].includes(day)){p.type='longform-outline';p.production.status='OUTLINE_READY_SCRIPT_REQUIRED';p.outline=['Open with a specific conflict', 'Examine one illustrative example','Separate facts from interpretations','Give one exercise','Review outcomes before optional offer'];}items.push({id:'day-'+String(day).padStart(2,'0'),package:p});}return items;}
function regenerate(p,feedback=[],alternate=false){const clone=JSON.parse(JSON.stringify(p));if(alternate){clone.regeneration=(clone.regeneration||0)+1;if(clone.type==='sales'){const hooks=['Everything needs you. What goes first?','What keeps taking your time?','Overwhelmed? What do you fix first?'];const hook=hooks[(clone.regeneration-1)%hooks.length];clone.title=hook+(clone.platform==='youtube'?' | The Freedom Audit':'');clone.scenes[0]={...clone.scenes[0],narration:hook,screen:hook};}else if(clone.titleCandidates?.length){clone.title=clone.titleCandidates[clone.regeneration%clone.titleCandidates.length];}}
 for(const key of ['title','description','cta'])clone[key]=applyLearning(clone[key],feedback);clone.scenes=clone.scenes.map(s=>({...s,narration:applyLearning(s.narration,feedback),screen:applyLearning(s.screen,feedback)}));clone.production.media=null;clone.production.review=null;clone.production.status=p.type==='longform-outline'?'OUTLINE_READY_SCRIPT_REQUIRED':p.platform==='tiktok'?'HOLD_TIKTOK_REVIEW_PENDING':'PACKAGE_READY_MEDIA_PENDING';return finish(clone);}
module.exports={catalog,calendar,variant,longPackage,short,finish,subtitles,regenerate,DESTINATIONS};


