const router=require('express').Router(),mongoose=require('mongoose'),asyncHandler=require('express-async-handler');
const {protect}=require('../middleware/authMiddleware'),{canRead,ownerId}=require('../enterprise/policy'),service=require('../enterprise/content/service'),workspace=require('../enterprise/content/workspaceConnection');
const db=()=>mongoose.connection.db;
const wrap=fn=>asyncHandler(async(req,res)=>{try{res.set('Cache-Control','private, no-store');await fn(req,res);}catch(e){res.status(e.statusCode||500).json({code:e.statusCode?e.message:'CONTENT_FACTORY_UNAVAILABLE'});}});
router.get('/google/callback',asyncHandler(async(req,res)=>{
 if(req.query.error)return res.redirect(302,workspace.commanderReturnUrl({workspace_status:'error',workspace_error:String(req.query.error).slice(0,120)}));
 if(!req.query.code||!req.query.state)return res.redirect(302,workspace.commanderReturnUrl({workspace_status:'error',workspace_error:'missing_oauth_code_or_state'}));
 try{const result=await workspace.handleCallback({code:String(req.query.code),state:String(req.query.state)});return res.redirect(302,workspace.commanderReturnUrl({workspace_status:'connected',workspace_account:result.accountEmail}));}
 catch(e){return res.redirect(302,workspace.commanderReturnUrl({workspace_status:'error',workspace_error:String(e.message||'workspace_connection_failed').slice(0,120)}));}
}));
router.use(protect,(req,res,next)=>canRead(req.user)&&service.active()?next():res.status(404).json({code:'NOT_FOUND'}));
router.get('/',wrap(async(_req,res)=>res.json(await service.list(db(),ownerId()))));
router.get('/connections',wrap(async(_req,res)=>res.json({connections:await db().collection('socialconnections').find({userId:new mongoose.Types.ObjectId(ownerId()),active:true},{projection:{provider:1,accountName:1,accountType:1}}).toArray()})));
router.get('/workspace/status',wrap(async(req,res)=>res.json(await workspace.getStatus({owner:ownerId(),verify:req.query.verify==='true'}))));
router.post('/workspace/connect',wrap(async(_req,res)=>res.json(await workspace.beginAuthorization({userId:ownerId()}))));
router.get('/workspace/assets',wrap(async(_req,res)=>res.json({assets:await workspace.listAssetLibrary({owner:ownerId()}),decisionEngine:{modes:['REUSE','GENERATE','COMBINE'],rule:'Reuse approved owned media when it supports the idea without misrepresentation; generate only when the concept requires new premium imagery; combine when one new scene plus approved plates is enough.'}})));
router.get('/workspace/vids-boundary',wrap(async(_req,res)=>res.json({mode:'HYBRID',capabilities:{createCopy:'BROWSER_AUTOMATABLE_WHILE_SESSION_AVAILABLE',organizeProjectInDrive:'FULLY_AUTOMATABLE_WITH_DRIVE_FILE_SCOPE_FOR_APP_CREATED_FILES',uploadReferenceIngredients:'FULLY_AUTOMATABLE',submitPremiumGeneration:'BROWSER_AUTOMATABLE_WHILE_SESSION_AVAILABLE',saveGeneratedResult:'BROWSER_AUTOMATABLE_WHILE_SESSION_AVAILABLE',insertGeneratedMedia:'BROWSER_AUTOMATABLE_WHILE_SESSION_AVAILABLE',timelineArrangement:'FOUNDER_OR_BROWSER_INTERACTION_REQUIRED',editableText:'FOUNDER_OR_BROWSER_INTERACTION_REQUIRED',narration:'DETERMINISTIC_POST_PRODUCTION_RECOMMENDED',music:'DETERMINISTIC_POST_PRODUCTION_RECOMMENDED',captions:'DETERMINISTIC_POST_PRODUCTION',export:'BROWSER_OR_DRIVE_DOWNLOAD_OPERATION',drivePersistence:'FULLY_AUTOMATABLE'},limitations:['No verified public Google Vids timeline-authoring API is implemented here.','Drive API can store app-created assets and initiate Google Vids MP4 download operations, but it does not provide scene-level Vids editing controls in this app.','drive.file can only access files the app created or the founder explicitly opened/selected for the app.']})));
router.post('/prepare',wrap(async(_req,res)=>res.json(await service.prepareDaily({db:db()}))));
router.post('/:id/google-slides',wrap(async(req,res)=>{if(Object.keys(req.body||{}).some(k=>k!=='expectedHash'))return res.status(400).json({code:'EXACT_VERSION_REQUIRED'});const data=await service.list(db(),ownerId()),item=data.items.find(i=>i.id===req.params.id);if(!item)return res.status(404).json({code:'NOT_FOUND'});if(item.hash!==req.body.expectedHash)return res.status(409).json({code:'CONTENT_VERSION_CHANGED'});const receiptId='c0:google:'+ownerId()+':'+item.hash;const previous=await db().collection('enterprisestates').findOne({_id:receiptId,owner:ownerId()});if(previous)return res.json(previous.result);const {accessToken}=await workspace.getFreshAccessToken({owner:ownerId()});const result=await require('../enterprise/content/googleProduction').createSlides({token:accessToken,package:item.package});await db().collection('enterprisestates').updateOne({_id:receiptId},{$setOnInsert:{owner:ownerId(),kind:'C0_GOOGLE_DRAFT',hash:item.hash,result,createdAt:new Date()}},{upsert:true});res.json(result);}));
router.post('/approve',wrap(async(req,res)=>{if(Object.keys(req.body||{}).some(k=>k!=='items'))return res.status(400).json({code:'EXACT_VERSIONS_REQUIRED'});res.json(await service.approveMany({db:db(),client:mongoose.connection.getClient(),owner:ownerId(),items:req.body.items}));}));
router.patch('/:id',wrap(async(req,res)=>{if(Object.keys(req.body||{}).some(k=>!['expectedHash','action','patch','feedback'].includes(k)))return res.status(400).json({code:'INVALID_CONTENT_ACTION'});res.json(await service.change({db:db(),owner:ownerId(),id:req.params.id,...req.body}));}));
router.post('/:id/media-review',wrap(async(req,res)=>{if(Object.keys(req.body||{}).some(k=>!['expectedHash','media','checks'].includes(k)))return res.status(400).json({code:'INVALID_MEDIA_REVIEW'});res.json(await service.attachReviewedMedia({db:db(),owner:ownerId(),id:req.params.id,...req.body}));}));
router.get('/:id/bundle',wrap(async(req,res)=>{const data=await service.list(db(),ownerId()),item=data.items.find(x=>x.id===req.params.id);if(!item)return res.status(404).json({code:'NOT_FOUND'});res.set('Content-Disposition',`attachment; filename="${item.id}-v${item.version}.json"`);res.json({version:item.version,hash:item.hash,voice:data.voice,productionPackage:item.package,qa:item.qa,googleWorkspace:await workspace.getStatus({owner:ownerId()}),googleVids:{assembly:'Import a prepared Slides deck or assemble the supplied scene inputs in Vids UI; no public timeline authoring API is verified in this app.',downloadApi:'POST https://www.googleapis.com/drive/v3/files/{fileId}/download?mimeType=video/mp4 using Drive long-running operations for Google Vids.',paidGeneration:'Not authorized',publicPublishing:'Not authorized'}});}));
module.exports=router;
