import { useEffect, useState, useCallback, useRef } from 'react';
import axios from 'axios';
import PatternObservationForm, { eventKey, typedValue } from './PatternObservationForm';
import './PatternPanel.css';
export default function PatternPanel(){
  const generation=useRef(0);
  const [ready,setReady]=useState(false);
  const [sourceOpen,setSourceOpen]=useState(false);
  const [enabled,setEnabled]=useState(false),[state,setState]=useState('active'),[rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[epoch,setEpoch]=useState(0),[nextCursor,setNextCursor]=useState(null);
  const [sources,setSources]=useState([]),[goals,setGoals]=useState([]),[tasks,setTasks]=useState([]),[preview,setPreview]=useState(null);
  const [rule,setRule]=useState({family:'recurrence',domain:'business',related:'',subject:'focus-block',metric:'completed',value:'true',before:'started',direction:'completed_as_intended',goalId:'',unit:'minutes',delta:'1'});
  const [intent,setIntent]=useState({taskId:'',goalId:'',due:'',subject:'focus-block'});
  const refresh=useCallback(async()=>{
    const ticket=++generation.current;setReady(false);setRows([]);setSources([]);setPreview(null);
    const capability=await axios.get('/api/core/patterns/capability');if(ticket!==generation.current)return;setEnabled(capability.data.enabled);if(!capability.data.enabled)return;
    const [patterns,observations,context,taskList]=await Promise.all([axios.get('/api/core/patterns',{params:{state}}),axios.get('/api/core/signals'),axios.get('/api/core/context'),axios.get('/api/core/tasks')]);
    if(ticket!==generation.current)return;
    setRows(patterns.data.patterns);setEpoch(patterns.data.sourceEpoch);setNextCursor(patterns.data.nextCursor);setSources((observations.data.entries||[]).filter(s=>s.event));setGoals(context.data.goals||[]);setTasks(taskList.data.tasks||[]);setReady(true);
  },[state]);
  useEffect(()=>{let mounted=true;const reload=()=>{if(mounted)refresh().catch(()=>{if(mounted)setError('Patterns could not be loaded.');});};reload();window.addEventListener('core-context-changed',reload);window.addEventListener('focus',reload);return()=>{mounted=false;generation.current++;window.removeEventListener('core-context-changed',reload);window.removeEventListener('focus',reload);};},[refresh]);
  const change=async operation=>{setBusy(true);setError('');setRows([]);setPreview(null);try{await operation();await refresh();}catch(e){setError(e.response?.data?.message||'The change could not be completed.');}finally{setBusy(false);}};
  const feedback=(p,action)=>change(()=>axios.post(`/api/core/patterns/${p.id}/feedback`,{action,expectedRevision:p.revision,requestId:crypto.randomUUID()}));
  async function moreEvidence(p,role){const ticket=generation.current;const field=role==='support'?'supportingEvidence':'contradictoryEvidence';try{const response=await axios.get(`/api/core/patterns/${p.id}/evidence`,{params:{role,offset:p[field].length}});if(ticket===generation.current)setRows(previous=>previous.map(x=>x.id===p.id?{...x,[field]:[...x[field],...response.data.entries]}:x));}catch{setRows([]);setError('Evidence changed. Reload.');}}
  async function openSource(id){const ticket=generation.current;try{const r=await axios.get(`/api/core/signals/${id}`);if(ticket===generation.current){setSources(previous=>[r.data,...previous.filter(s=>s._id!==id)]);setSourceOpen(true);}}catch{setSources([]);setError('This observation is no longer available.');}}
  async function morePatterns(){const ticket=generation.current;try{const r=await axios.get('/api/core/patterns',{params:{state,cursor:nextCursor}});if(ticket===generation.current){setRows(previous=>[...previous,...r.data.patterns]);setNextCursor(r.data.nextCursor);}}catch{setRows([]);setError('Patterns changed. Reload.');}}
  async function propose(e){e.preventDefault();const value={family:rule.family,domain:eventKey(rule.domain),subjectKey:eventKey(rule.subject),conditions:[]};
    value.relatedDomains=rule.related.split(',').map(eventKey).filter(Boolean);
    if(['recurrence','sequence'].includes(rule.family))value.outcome={key:eventKey(rule.metric),op:'eq',value:typedValue(rule.value)};
    if(rule.family==='sequence')value.antecedent={key:eventKey(rule.before),op:'eq',value:true};
    if(rule.family==='goal_action_consistency')Object.assign(value,{goalId:rule.goalId,direction:rule.direction});
    if(rule.family==='intervention_response')Object.assign(value,{metricKey:eventKey(rule.metric),unit:eventKey(rule.unit),direction:['increase','decrease','unchanged'].includes(rule.direction)?rule.direction:'increase',minimumDelta:Number(rule.delta)});
    await change(()=>axios.post('/api/core/patterns/hypotheses',{rule:value,expectedSourceEpoch:epoch}));
  }
  const ruleField=(key,label)=><label>{label}<input value={rule[key]} maxLength={80} required onChange={e=>setRule({...rule,[key]:e.target.value})}/></label>;
  if(!enabled)return null;
  return <section className="mentor-card pattern-panel" aria-label="Patterns"><h2>Patterns</h2><p>Recurring evidence, open to correction. Evaluation creates no tasks or autonomous actions.</p>
    <label>Show<select value={state} onChange={e=>setState(e.target.value)} disabled={busy}>{['active','candidate','disputed','dismissed','retired'].map(s=><option key={s} value={s}>{s==='candidate'?'Possible patterns to review':s}</option>)}</select></label>
    <button disabled={busy||!ready} onClick={()=>change(()=>axios.post('/api/core/patterns/evaluate',{expectedSourceEpoch:epoch}))}>Evaluate recorded evidence</button>
    {error&&<p role="alert">{error}</p>}{busy&&<p role="status">Checking your records…</p>}{!busy&&!rows.length&&<p>No patterns in this view. Not enough recorded evidence yet is a valid result.</p>}
    {rows.map(p=><article key={p.id}><h3>{p.hypothesis||'Pattern needs review'}</h3><p>{p.state} · {p.confidence||'not evaluated'}</p><p>{p.message}</p>
      {p.freshness==='current'&&<><p>Recorded activity: {p.rule.subjectKey}. {p.counts.supportingUnits} supporting episodes across {p.counts.supportDates} dates; {p.counts.contradictingUnits} contradictory episodes; {p.counts.distinctSourceObservations} distinct source records.</p>
        <p>{new Date(p.window.start).toLocaleDateString()}–{new Date(p.window.end).toLocaleDateString()} · UTC · {p.methodVersion}</p>
        <details><summary>Evidence and alternative explanations</summary><h4>Supporting evidence</h4><ul>{p.supportingEvidence.map(r=><li key={r.recordId}>{r.excerpt} · {r.source} · {new Date(r.occurredAt).toLocaleString()}{r.authority==='SignalEntry'&&<button onClick={()=>openSource(r.recordId)}>Review source observation</button>}</li>)}</ul><h4>Contradictory evidence</h4>{p.contradictoryEvidence.length?<ul>{p.contradictoryEvidence.map(r=><li key={r.recordId}>{r.excerpt} · {r.source}{r.authority==='SignalEntry'&&<button onClick={()=>openSource(r.recordId)}>Review source observation</button>}</li>)}</ul>:<p>No contradictory observations were recorded in this evaluated window. This does not establish complete coverage.</p>}
          {p.alternatives.map(a=><p key={a}>{a}</p>)}<p>{p.suggestedNextStep}</p>
          <button onClick={()=>moreEvidence(p,'support')} disabled={p.supportingEvidence.length>=p.supportingEvidenceCount}>More supporting evidence</button>
          <button onClick={()=>moreEvidence(p,'contradiction')} disabled={p.contradictoryEvidence.length>=p.contradictoryEvidenceCount}>More contradictory evidence</button>
        </details><button disabled={busy} onClick={()=>feedback(p,'agree')}>This fits</button></>}
      <button disabled={busy} onClick={()=>feedback(p,'dispute')}>This doesn’t fit</button><button disabled={busy} onClick={()=>feedback(p,'dismiss')}>Don’t show this again</button><button disabled={busy} onClick={()=>feedback(p,'retire')}>No longer relevant</button>
      {['dismissed','disputed','retired'].includes(p.state)&&<button disabled={busy} onClick={()=>feedback(p,'reopen')}>Reopen for evaluation</button>}{p.reopenEligible&&<p>New recorded evidence is available for your review.</p>}
    </article>)}
    {nextCursor&&<button onClick={morePatterns}>More patterns</button>}
    <PatternObservationForm onChanged={refresh} tasks={tasks}/>
    <details open={sourceOpen} onToggle={e=>setSourceOpen(e.currentTarget.open)}><summary>Review or correct observations</summary>{sources.map(s=><form key={s._id+':'+s.revision} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const values=Object.fromEntries(Object.keys(s.event.values||{}).map(k=>[k,typedValue(form.get('value-'+k))]));change(()=>axios.patch(`/api/core/signals/${s._id}`,{expectedRevision:s.revision,notes:form.get('notes'),event:{...s.event,values}}));}}><p>{s.event.subjectKey} · {new Date(s.occurredAt).toLocaleString()}</p>{Object.entries(s.event.values||{}).map(([k,v])=><label key={k}>Recorded {k}<input name={'value-'+k} defaultValue={String(v)}/></label>)}<label>Observation notes<input name="notes" defaultValue={s.notes||''}/></label><button disabled={busy}>Save observation correction</button><button type="button" disabled={busy} onClick={()=>change(()=>axios.delete(`/api/core/signals/${s._id}`,{headers:{'If-Match':String(s.revision)}}))}>Delete observation</button></form>)}</details>
    <details><summary>Ask about a possible pattern</summary><p>This proposes a hypothesis. It does not create observations or establish that it is true.</p><form onSubmit={propose}><label>Pattern family<select value={rule.family} onChange={e=>setRule({...rule,family:e.target.value})}><option value="recurrence">Repeated outcome</option><option value="sequence">One event before another</option><option value="goal_action_consistency">Intention and completion</option><option value="intervention_response">Outcome after an intervention</option></select></label>{ruleField('domain','Area of life')}{ruleField('subject','Activity or situation')}
      <label>Additional areas, separated by commas (optional)<input value={rule.related} onChange={e=>setRule({...rule,related:e.target.value})}/></label>
      {rule.family!=='goal_action_consistency'&&ruleField('metric','Recorded outcome to examine')}{['recurrence','sequence'].includes(rule.family)&&ruleField('value','Outcome value')}{rule.family==='sequence'&&ruleField('before','Earlier event (recorded as true)')}
      {rule.family==='goal_action_consistency'&&<><label>Goal<select required value={rule.goalId} onChange={e=>setRule({...rule,goalId:e.target.value})}><option value="">Choose a goal</option>{goals.map(g=><option key={g._id} value={g._id}>{g.description}</option>)}</select></label><label>Outcome<select value={rule.direction} onChange={e=>setRule({...rule,direction:e.target.value})}><option value="completed_as_intended">Completed as intended</option><option value="recorded_not_completed_as_intended">Recorded as not completed as intended</option></select></label></>}
      {rule.family==='intervention_response'&&<>{ruleField('unit','Measurement unit')}{ruleField('delta','Minimum meaningful change')}<label>Direction<select value={rule.direction} onChange={e=>setRule({...rule,direction:e.target.value})}><option value="increase">Increase</option><option value="decrease">Decrease</option><option value="unchanged">No meaningful change</option></select></label></>}
      <button disabled={busy}>Review hypothesis</button></form></details>
    <details><summary>Record an explicit task intention</summary><form onSubmit={e=>{e.preventDefault();const task=tasks.find(t=>t._id===intent.taskId);change(()=>axios.patch(`/api/core/tasks/${intent.taskId}/intent`,{goalId:intent.goalId,dueAt:new Date(intent.due).toISOString(),subjectKey:eventKey(intent.subject),expectedRevision:task.revision||0}));}}><label>Existing task<select required value={intent.taskId} onChange={e=>setIntent({...intent,taskId:e.target.value})}><option value="">Choose a task</option>{tasks.map(t=><option key={t._id} value={t._id}>{t.description}</option>)}</select></label><label>Goal<select required value={intent.goalId} onChange={e=>setIntent({...intent,goalId:e.target.value})}><option value="">Choose a goal</option>{goals.map(g=><option key={g._id} value={g._id}>{g.description}</option>)}</select></label><label>Planned completion<input required type="datetime-local" value={intent.due} onChange={e=>setIntent({...intent,due:e.target.value})}/></label><label>Activity<input required value={intent.subject} onChange={e=>setIntent({...intent,subject:e.target.value})}/></label><button disabled={busy}>Save task intention</button></form></details>
    <button disabled={busy} onClick={()=>axios.get('/api/core/patterns/plan-preview').then(r=>setPreview(r.data)).catch(()=>setError('The planning draft is unavailable.'))}>Preview a plan</button>{preview&&<div><p>{preview.message}</p><ul>{preview.suggestions.map(t=><li key={t.taskId}>{t.description}</li>)}</ul></div>}
  </section>;
}
